import type { Metadata } from "next";
import "./globals.css";
import "@/components/ColorBends";
import ColorBends from "../components/ColorBends";
import Navbar from "@/components/ui/navbar";
import Background from "@/components/ui/background";
import { Roboto } from "next/font/google";
import { cn } from "@/lib/utils";

const roboto = Roboto({subsets:['latin'],variable:'--font-sans'});


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("dark", "font-sans", roboto.variable)}>
      <body className="relative">
          <Background/>
        {children}
      </body>
    </html>
  );
}
